config/routes.rb
Rails.application.routes.draw do
  root 'cats#index'
  resources :cats
  resources :tasks
end

app/models/cat.rb
class Cat < ActiveRecord::Base
    has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :cat
  default_scope -> { order(created_at: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  
  def index
    @cats = Cat.all
    @tasks = Task.all
  end
  
  def show
    @cat =Cat.find(params[:id])
    @Tasks = @cat.tasks.paginate(page: params[:page])
    @task  = Task.new
  end
  
  def new
    @cat = Cat.new
  end
  
  def create
    @cat = Cat.new(cat_params)    
    if @cat.save
      flash[:success] = "Category Created"
      redirect_to @cat
    else
      render 'new'
    end
  end
  
  def edit
    @cat = Cat.find(params[:id])
  end
  
  def update
   @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      flash[:success] = "Category Edited"
      redirect_to @cat
    else
      render 'edit'
    end
  end
  
  def destroy
    Cat.find(params[:id]).destroy
    flash[:success] = "Category Deleted"
    redirect_to '/'
  end
  
  private
  
    def cat_params
      params.require(:cat).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  def show
     @task = Task.find(params[:id])
  end
  
  def new
      @task=Task.new
  end
  
  
  def create
    @task=Task.new(task_params)
    if @task.save
      flash[:success] = "task created!"
      if @task.done == true
          @task.cat_id =2
          @task.save
          redirect_to '/cats/2'
      else
          @task.cat_id =1
          @task.save
          redirect_to '/cats/1'
      end
    else
      render '/'
    end
  end
  
  def edit
    @task = Task.find(params[:id])
  end
  
  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      flash[:success] = "Task Edited"
      if @task.done == true
          @task.cat_id =2
          @task.save
          redirect_to '/cats/2'
      else
          @task.cat_id =1
          @task.save
          redirect_to '/cats/1'
      end
    else
      render 'edit'
    end
  end

  def destroy
    Task.find(params[:id]).destroy
    flash[:success] = "Category Deleted"
    redirect_to '/'
  end
  
  private

    def task_params
      params.require(:task).permit(:name, :need, :fix, :issue, :done, :cat_id, :subject )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/cats/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@cat) do |f| %>
      <%= f.label "Category Name" %><br>
      <%= f.text_field :name %>
      <%= f.submit "Create Category", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/cats/edit.html.erb
<h1>Edit Category</h1>
<%= render 'form' %>

app/views/cats/index.html.erb
<h2>Lists</h2><hr>
<% @cats.each do |cat| %>
<h1 style="width:50%;float:left;"><%= link_to cat.name, cat %>(<%=cat.tasks.count %>) 
</h1>
<%end %>
<h2 style="padding-top:115px;">Tasks</h2>
<hr>
<% @tasks.each do |task| %>
<li><%= link_to task.name, task %> |
        <%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' } %>
</li>
<%end %>

app/views/cats/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

app/views/cats/show.html.erb
<h1>
    <%= @cat.name %>
</h1>
<div class="col-md-8">
    <% if @cat.tasks.any? %>
      <h3>Tasks (<%= @cat.tasks.count %>)</h3>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Date</th>
      <th>Last Updated</th>
      <th>Change Status</th>
    </tr>
  </thead>

  <tbody>
    <% @Tasks.each do |task| %>
      <tr>
        <td class='<%= task.subject %>'></td>
        <td><%= link_to task.name, edit_task_path(task) %></td>
        <td><% if task.created_at? %><%= task.created_at.to_time.strftime('%D') %><% else %> -<% end %></td>
        <td><% if task.updated_at? && task.created_at? && task.updated_at.to_time.strftime('%A%B%Y%l%M%S') != task.created_at.to_time.strftime('%A%B%Y%l%M%S') %><%= task.updated_at.to_time.strftime('%D') %><% else %> -<% end %></td>        
        <td>    <%= form_for(task) do |f| %>
                    <%= f.hidden_field :done, :value => !task.done %>
                    <%= f.submit "Change Status", class: "btn-primary", style: "width:auto" %>
                <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
</div>

app/views/layouts/_head.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Tasks", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "New Task", '/tasks/new'%></li>
              <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Categories <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Todo", '/cats/1' %></li>
              <li><%= link_to "Done", '/cats/2' %></li>
            </ul>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Old Archives <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Trello", 'https://trello.com/b/NUB8Ssf9/work' %></li>
              <li><%= link_to "Google Spreadsheets", 'https://docs.google.com/spreadsheets/d/1m32QP83rRfj3PRhkWptBrq-ekW3hqhC-K0rnkKrzwjU/edit' %></li>
            </ul>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasks | Jonathan Schenk</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/head' %>
    <div class="container stuff">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_task.html.erb
<strong><%= link_to task.name, edit_task_path(task), style: "float:left;" %></strong>
    <%= form_for(task) do |f| %>
      <%= f.hidden_field :done, :value => !task.done %>
      <%= f.submit "Change Status", class: "btn-primary", style: "width:auto" %>
    <% end %>
<ul>
    <% if task.need? %>
        <li><%= task.need %></li>
    <%end%>
    <% if task.fix? %>
        <li><%= task.fix %></li>
    <% end %>
    <% if task.issue? %>
        <li><%= task.issue %></li>
    <% end %>
</ul>

app/views/tasks/_task_form.html.erb
<%= form_for(@task) do |f| %>
<div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Subject" %><br>
    <%= f.select( :subject, [[@task.subject],['Website'],['Inventory'],['Tracking'],['SEO/CRO','SEO']]) %>
  </div>
  <div class="field">
    <%= f.label :need %><br>
    <%= f.text_area :need %>
  </div>
  <div class="field">
    <%= f.label :fix %><br>
    <%= f.text_area :fix %>
  </div>
  <div class="field">
    <%= f.label :issue %><br>
    <%= f.text_area :issue %>
  </div>
  <div class="field">
    <%= f.label :done %><br>
    <%= f.check_box :done %>
  </div>
  <div class="actions">
    <%= f.submit "Continue", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1 class="text-center">Edit Task - <%= @task.name %></h1>
<%= render 'tasks/task_form' %>

app/views/tasks/new.html.erb
<h1 class="text-center">New Task</h1>
<%= render 'tasks/task_form' %>

app/views/tasks/show.html.erb
<%= render @task %>